name: Magento 2.1 CI

on:
  - push

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Launch Magento test environment
        run: make up-71

      - name: Run install script
        run: >-
          docker-compose exec -T web bash -c 'dockerize -wait tcp://db:3306 -timeout 60m /usr/local/bin/install-magento'
        env:
          COMPOSE_INTERACTIVE_NO_CLI: "1"

      - name: Set Base URL
        run: make fix-session-expire

      - uses: cypress-io/github-action@v1
        with:
          project: ./test/e2e
        env:
          CYPRESS_API_KEY: ${{ secrets.API_KEY }}
          MAGENTO_VERSION: "2.2"
